# frozen_string_literal: true

require "pathname"

module RubySage
  module AgentScan
    # Renders the +INSTRUCTIONS.md+ file the planner drops alongside a manifest.
    # A coding agent reads this once and produces +summaries.json+; the file is
    # written in plain Markdown and quotes the manifest schema verbatim so the
    # agent does not have to infer a contract.
    class Instructions
      # @param manifest [Hash] the manifest hash about to be written.
      # @param output_dir [Pathname] directory the manifest is written to.
      # @return [RubySage::AgentScan::Instructions]
      def initialize(manifest:, output_dir:)
        @manifest = manifest
        @output_dir = Pathname(output_dir)
      end

      # Returns the rendered Markdown body.
      #
      # @return [String]
      def render
        sections = [
          header,
          quick_summary,
          how_to_run,
          summary_prompt_section,
          output_format_section,
          rules_section,
          footer
        ]
        "#{sections.join("\n\n").strip}\n"
      end

      private

      attr_reader :manifest, :output_dir

      def header
        <<~MD.strip
          # RubySage agent scan — instructions

          You are summarizing files in a Ruby on Rails application so RubySage can
          answer code questions about it later. The host developer is using you
          (their local coding agent) instead of paying RubySage's LLM provider for
          the same work.
        MD
      end

      def quick_summary
        total = manifest["files"].size
        pending = manifest["files"].count { |entry| entry["needs_summary"] }
        reused = total - pending

        <<~MD.strip
          ## What you are looking at

          - `#{MANIFEST_FILENAME}` — #{total} files in this scan. #{pending} need a
            new summary; #{reused} can reuse a cached summary from a prior scan.
          - You will write `#{SUMMARIES_FILENAME}` in this same directory.
          - File contents in the manifest are already redacted for secrets — read
            from `redacted_contents`, NOT from disk, so you do not see live keys.
        MD
      end

      def how_to_run
        <<~MD.strip
          ## How to run

          1. Open `#{MANIFEST_FILENAME}`.
          2. For each entry where `needs_summary` is `true`, read its
             `redacted_contents` and write a summary using the prompt below.
          3. Write your output to `#{SUMMARIES_FILENAME}` in the format shown in
             "Output format".
          4. Tell the developer you are done. They will run
             `bundle exec rake ruby_sage:scan:apply`.

          Skip entries where `needs_summary` is `false` — their summaries are
          already cached and the apply step will reuse them.
        MD
      end

      def summary_prompt_section
        <<~MD.strip
          ## Summary prompt

          Use this exact instruction when summarizing each file:

          > #{manifest['summary_system_prompt'].lines.map(&:strip).join(' ')}
        MD
      end

      def output_format_section
        example = {
          "schema_version" => SCHEMA_VERSION,
          "summaries" => {
            "app/models/user.rb" => "The User model represents a signed-in account...",
            "app/controllers/posts_controller.rb" => "PostsController exposes CRUD..."
          }
        }
        <<~MD.strip
          ## Output format

          Write `#{SUMMARIES_FILENAME}` as a JSON file with this shape:

          ```json
          #{JSON.pretty_generate(example)}
          ```

          Keys are file paths exactly as they appear in the manifest. Values are
          the summary strings. Only include entries you actually summarized.
        MD
      end

      def rules_section
        <<~MD.strip
          ## Rules

          - Read `redacted_contents` from the manifest. Do not read the original
            file from disk — that bypasses the secret redaction layer.
          - Never include secret values, raw API keys, passwords, or
            personally-identifying data in a summary, even if you somehow see them.
            Mention `ENV["FOO"]` symbol references only.
          - Be specific. Mention public class/module names, key public methods,
            and how the file relates to the rest of the app. No fluff. No
            preamble like "This file is...".
          - 1-2 paragraphs per file. Longer is not better.
          - If a file looks empty, autogenerated, or unworth summarizing, write a
            single short sentence rather than skipping it — apply still needs an
            entry to mark it as processed.
        MD
      end

      def footer
        <<~MD.strip
          ---

          Manifest written to: `#{output_dir.join(MANIFEST_FILENAME)}`
          Write summaries to:  `#{output_dir.join(SUMMARIES_FILENAME)}`
        MD
      end
    end
  end
end
