# frozen_string_literal: true

require "fileutils"
require "pathname"

module RubySage
  module Artifacts
    # Owns the on-disk layout of `<host_root>/.ruby_sage/` — directory
    # creation, the default `.gitignore`, and path resolution.
    #
    # Pulled out of {DiskStore} so that I/O concerns (read/write/each artifact)
    # stay separate from layout/initialization concerns.
    class Layout
      ROOT_DIRNAME = ".ruby_sage"
      ARTIFACTS_DIRNAME = "artifacts"
      MANIFEST_FILENAME = "manifest.json"
      GITIGNORE_FILENAME = ".gitignore"
      ARTIFACT_EXTENSION = ".yml"

      DEFAULT_GITIGNORE = <<~IGNORE
        # Generated by RubySage. The on-disk artifact layout is the source of
        # truth for the codebase MCP server, so by default we keep it tracked.
        # If you would rather regenerate it locally, uncomment the lines below.
        #
        # *
        # !.gitignore
      IGNORE
      private_constant :DEFAULT_GITIGNORE

      # @param host_root [String, Pathname]
      def initialize(host_root:)
        @host_root = Pathname(host_root).expand_path
      end

      # @return [Pathname] absolute path to `.ruby_sage/`.
      def root
        host_root.join(ROOT_DIRNAME)
      end

      # @return [Pathname] absolute path to `.ruby_sage/artifacts/`.
      def artifacts_root
        root.join(ARTIFACTS_DIRNAME)
      end

      # @return [Pathname] absolute path to `.ruby_sage/manifest.json`.
      def manifest_path
        root.join(MANIFEST_FILENAME)
      end

      # @return [Pathname] absolute path to `.ruby_sage/.gitignore`.
      def gitignore_path
        root.join(GITIGNORE_FILENAME)
      end

      # Creates `.ruby_sage/` + `artifacts/` and seeds `.gitignore` if missing.
      #
      # @return [void]
      def ensure
        FileUtils.mkdir_p(artifacts_root)
        write_default_gitignore unless gitignore_path.file?
      end

      # @param path [String] host-relative file path.
      # @return [Pathname] absolute path for the matching `<path>.yml` artifact.
      def artifact_path_for(path)
        artifacts_root.join("#{path}#{ARTIFACT_EXTENSION}")
      end

      # @param candidate [String, Pathname] absolute path under {artifacts_root}.
      # @return [String] the host-relative path that produced this artifact file.
      def relative_to_artifacts(candidate)
        rel = Pathname(candidate).relative_path_from(artifacts_root).to_s
        rel.sub(/#{Regexp.escape(ARTIFACT_EXTENSION)}\z/, "")
      end

      # Removes empty subdirectories under {artifacts_root}.
      #
      # @return [void]
      def prune_empty_artifact_dirs
        Pathname.glob(artifacts_root.join("**/*"))
                .select(&:directory?)
                .sort_by { |p| -p.to_s.length }
                .each { |dir| dir.rmdir if dir.children.empty? }
      end

      private

      attr_reader :host_root

      def write_default_gitignore
        FileUtils.mkdir_p(root)
        File.write(gitignore_path, DEFAULT_GITIGNORE)
      end
    end
  end
end
